apiVersion: v1
kind: Service
metadata:
  name: {{ template "dummy-server-chart.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ template "dummy-server-chart.fullname" . }}-svc
spec:
  ports:
  - port: {{ .Values.images.dummy_server.port }}
    name: http
  selector:
    app: {{ template "dummy-server-chart.fullname" . }}-depl
  type: ClusterIP
