apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dummy-server-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
data:
  # echo -n "Happy GPG-Secret" | base64
  api-exposed: SGFwcHkgR1BHLVNlY3JldA==
